In [22]:
import numpy as np

In [4]:
array1 = numpy.array([2, 3, 5, 6])

In [5]:
print(array1)

[2 3 5 6]


In [6]:
array2 = numpy.full(6,7) # (개수, 동일하게 나올 숫자)

In [7]:
print(array2)

[7 7 7 7 7 7]


In [8]:
array3 = numpy.full(6, 1)

In [9]:
print(array3)

[1 1 1 1 1 1]


In [10]:
array4 = numpy.ones(6, dtype=int)

In [11]:
print(array4)

[1 1 1 1 1 1]


In [12]:
array5 = numpy.random.random(6)
array6 = numpy.random.random(6)

In [13]:
print(array5)

[0.09908314 0.19069887 0.72310213 0.90062886 0.96192379 0.65280992]


In [14]:
print(array6)

[0.12330692 0.81731719 0.2563633  0.07671306 0.6914942  0.2368691 ]


In [15]:
array7 = numpy.arange(6)
print(array7)

[0 1 2 3 4 5]


In [25]:
array8 = numpy.arange(3,9)

In [26]:
print(array8)

[3 4 5 6 7 8]


In [18]:
array9 = numpy.arange(1,20, 2)
print(array9)

[ 1  3  5  7  9 11 13 15 17 19]


In [24]:
array10 = np.random.randint(0, 10) #정수값 중 랜덤
print(array10)

2


In [23]:
array11 = np.full(6, 3) # 앨리어싱
print(array11)

[3 3 3 3 3 3]


In [27]:
arr = np.arange(1, 101)
arr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [28]:
arr2 = np.arange(3, 101, 3)
arr2

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
       54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])