In [1]:
import numpy as np

In [2]:
array1 = np.array([2, 3, 5, 6, 8, 11, 13, 17, 19, 23, 29, 31])

In [3]:
array1[0]

2

In [5]:
array1[2]

5

In [8]:
print(array1[-1])
array1[-2]

31


29

In [9]:
array1[[0, 1, 2]] #0, 1, 2번 인덱스를 출력한다.

array([2, 3, 5])

In [10]:
array2 = np.array([2, 3, 5]) #array index
array1[array2]

array([ 5,  6, 11])

In [11]:
array1[2:7]

array([ 5,  6,  8, 11, 13])

In [12]:
array1[:7]

array([ 2,  3,  5,  6,  8, 11, 13])

In [13]:
array1[3:]

array([ 6,  8, 11, 13, 17, 19, 23, 29, 31])

In [15]:
array1[2:11:2] #하나씩 건너 뛰겠다.

array([ 5,  8, 13, 19, 29])

In [16]:
#numpy는 기본 파이썬과 다르게 array 연산이 가능하다.

In [17]:
arr1 = np.arange(10)
arr2 = np.arange(10, 20)

In [18]:
arr1 #여기에 2를 곱하려면

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
for i in range(len(arr1)): #기존
    arr1[i] = 2 * arr1[i]
arr1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [21]:
arr1 = np.arange(10)

In [22]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
arr1 * 2 # numpy array는 연산이 가능

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [24]:
arr1 + 1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
arr1 + arr2

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [26]:
arr1 / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [28]:
arr1 ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)